#!/usr/bin/env python3

import rospy 
from geometry_msg.msg import Twist

PI=3.1415926535897
def move():

    rospy.init_node("turtlemove",anonymous =True)
    pub=rospy.Publisher("/turtle1/cmd_vel",Twist,queue_size=10)
    rate= rospy.Rate(10)
    vel=Twist()
    speed=input("speed:")
    distance=input("distance:")

    while True:
        vel.linear.x=speed
        vel.linear.y=0
        vel.lenear.z=0

        vel.angular.x=0
        vel.angular.y=0
        vel.angular.z=0
        t0=rospy.Time.now().to_sec()
        current_distance=0
        while (current_distance<distance):


            pub.publish(vel)
            t1=rospy.Time.now()to_sec()
            current_distance=speed*(t1-t0)
            rate.sleep()
  
def turn():
    rospy.init_node("turtlemove",anonymous =True)
    pub=rospy.Publisher("/turtle1/cmd_vel",Twist,queue_size=10)
    rate= rospy.Rate(10)
    vel=Twist()
    angle=PI /2
    speed=50*2*PI/360
    while True:

        vel.linear.x=0
        vel.linear.y=0
        vel.lenear.z=0

        vel.angular.x=0
        vel.angular.y=0
        vel.angular.z=speed
        t0 = rospy.Time.now().to_sec()
        current_angle=0
        while (current_angle < angle):
            pub.publish(vel)
            t1=rospy.Time.now()to_sec()
            current_angle=speed*(t1-t0)

            rate.sleep()
if __name__='__main___':

    for i in range(4):
        move()
        turn()
